spring:
  redis:
    host: ${REDIS_HOST:host.docker.internal}
    port: ${REDIS_PORT:6379}
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0
    redisson:
      config:
        singleServerConfig:
          idleConnectionTimeout: 10000
          pingTimeout: 1000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          reconnectionTimeout: 3000
          failedAttempts: 3
          subscriptionsPerConnection: 5
          clientName: null
          database: 0
          password: null
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 32
          connectionPoolSize: 64
          dnsMonitoring: false
          dnsMonitoringInterval: 5000
        threads: 0
        nettyThreads: 0
        codec: "org.redisson.codec.JsonJacksonCodec"
        transportMode: "NIO"
  dubbo:
    application:
      id: com-saas-sisyphus
      name: sisyphus
    registry:
      address: zookeeper://${ZOOKEEPER_HOST:host.docker.internal}:${ZOOKEEPER_PORT:2181}
    server: true
    protocol:
      name: dubbo
      port: 20880