version: "3"
services:
  nacos:
    image: nacos/nacos-server:2.0.0-bugfix
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos_devtest
      - MYSQL_SERVICE_PORT=3307
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    env_file: .env
    expose:
      - 8848
    depends_on:
      - nacos-mysql
    restart: on-failure
    networks:
      backend:
        aliases:
          - nacos-standalone
  nacos-mysql:
    container_name: nacos-mysql
    image: nacos/nacos-mysql:5.7
    environment:
      - MYSQL_DATABASE=nacos_devtest
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    env_file: .env
    expose:
      - 3307
    networks:
      backend:
        aliases:
          - nacos-mysql
  mysql:
    container_name: mysql
    image: mysql:5.7.31
    restart: always
    ports:
      - 3306:3306
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: 'root'
      MYSQL_PASS: '123456'
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--max_connections=3000'
    ]
    networks:
      backend:
        aliases:
          - mysql
  redis:
    container_name: redis_1
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    env_file: .env
    expose:
      - 6379
    networks:
      backend:
        aliases:
          - redis_1
  zookeeper_1:
    container_name: zookeeper_1
    image: zookeeper:latest
    restart: always
    ports:
      - 2181:2181
    env_file: .env
    expose:
      - 2181
    networks:
      backend:
        aliases:
          - zookeeper_1
  zookeeper_2:
    container_name: zookeeper_2
    image: zookeeper:latest
    restart: always
    ports:
      - 2182:2181
    env_file: .env
    expose:
      - 2182
    networks:
      backend:
        aliases:
          - zookeeper_2
  zookeeper_3:
    container_name: zookeeper_3
    image: zookeeper:latest
    restart: always
    ports:
      - 2183:2181
    env_file: .env
    expose:
      - 2183
    networks:
      backend:
        aliases:
          - zookeeper_3
networks:
  backend: