version: "3"
services:
  nacos:
    image: nacos/nacos-server:2.0.0-bugfix
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos_devtest
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    env_file: .env
    expose:
      - 8848
    depends_on:
      - mysql
    restart: on-failure
    networks:
      backend:
        aliases:
          - nacos-standalone
  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:5.7
    environment:
      - YSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nacos_devtest
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=root
      - MYSQL_RANDOM_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file: .env
    expose:
      - 3306
    networks:
      backend:
        aliases:
          - mysql
  redis:
    container_name: redis_1
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    env_file: .env
    expose:
      - 6379
    networks:
      backend:
        aliases:
          - redis_1
  zookeeper_1:
    container_name: zookeeper_1
    image: zookeeper:latest
    restart: always
    ports:
      - 2181:2181
    env_file: .env
    expose:
      - 2181
    networks:
      backend:
        aliases:
          - zookeeper_1
  zookeeper_2:
    container_name: zookeeper_2
    image: zookeeper:latest
    restart: always
    ports:
      - 2182:2181
    env_file: .env
    expose:
      - 2182
    networks:
      backend:
        aliases:
          - zookeeper_2
  zookeeper_3:
    container_name: zookeeper_3
    image: zookeeper:latest
    restart: always
    ports:
      - 2183:2181
    env_file: .env
    expose:
      - 2183
    networks:
      backend:
        aliases:
          - zookeeper_3
networks:
  backend: